name = "Alg4Env"
uuid = "b7b2f5d4-9f61-4f3f-9d7b-9d1b0f1b8e9a"
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DotProductGraphs = "586abeb4-6645-4f28-8984-da840f878f37"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15"
Colors = "0.13.1"
DotProductGraphs = "0.2"
OrdinaryDiffEq = "6"
Serialization = "1.11.0"
